echo "<div id='myModal' class='modal'>";
    echo "<div class='modal-content'>";
        echo "<span class='close'>&times;</span>";
        echo "<img src='".$pic['img']."' alt=''>";
        // echo '<img id="myImg" onclick="showImage(this)" src="'.$pic['img'].'" class="photo" />';
        echo "</br><a href=index.php?action=likeUp&id=".($pic['id_img']).">Like : ". count_like($pic['id_img']) ."</a>";
        echo "<a href=''> | Comment</a>";
        echo " | id : ".$pic['id_img'];
    echo "</div>";
echo "</div>";